---
title: "create_gif"
author: "yiru wang"
date: '2022-11-09'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(gganimate)
library(tidyverse)
library(spotoroo)
library(rnaturalearth)
library(ggplot2)
library(ggthemes)
```

```{r}
d <- read_csv("data/hotspot_2019_2020.csv")%>%
  as.data.frame()

result <- hotspot_cluster(d,
  lon = "lon",
  lat = "lat",
  obsTime = 'obsTime',
  activeTime = 24,
  adjDist = 3000,
  minPts = 4,
  minTime = 3,
  ignitionCenter = "mean",
  timeUnit = "h",
  timeStep = 1
)

result_data <- result$hotspots%>%
  mutate(membership = as.factor(membership))

result_data2 <- result_data%>%
  select(lon,lat,membership)

vic_map = ne_states(country = 'Australia', returnclass = 'sf')%>%
  filter(name == "Victoria")

p = ggplot(result_data) +
  geom_sf(data = vic_map, fill = "#2D2C2C",colour="white") +
  xlim(c(140, 150.5)) + ylim(c(-39.5, -33.5)) +
  ggtitle("Monthly Average Temperature") +
  theme_map() +
  exit_fade() +
  enter_fade() +
  #theme(panel.background = element_blank())+
  theme(legend.position="none")+
  geom_point(mapping = aes(x = lon, y = lat,color = membership)
             , alpha = 0.2)+
  transition_time(obsTime) +
  labs(title = 'Time: {frame_time}',size = 12)


animate(p,fps = 7)
anim_save(filename = '2019_2020.gif',path = "./www/")
```


```{r}
a = ggplot(result_data) +
  geom_sf(data = vic_map) +
  geom_point(aes(x = lon, y = lat,color = membership), alpha = 0.2) + 
  theme_bw()+
  theme(legend.position='none')
a
```


```{r}
d <- read_csv("data/vic_hist_hotspot.csv")%>%
  mutate(date = as.Date(datetime))%>%
  mutate(obsTime = as_datetime(datetime))%>%
  mutate(obsTime = as.POSIXct(obsTime))%>%
  extract(geometry, c('lon', 'lat'), '\\((.*), (.*)\\)', convert = TRUE)

result <- hotspot_cluster(d,
  lon = "lon",
  lat = "lat",
  obsTime = 'obsTime',
  activeTime = 24,
  adjDist = 3000,
  minPts = 4,
  minTime = 3,
  ignitionCenter = "mean",
  timeUnit = "h",
  timeStep = 1
)

result_data <- result$hotspots%>%
  mutate(membership = as.factor(membership))

vic_map = ne_states(country = 'Australia', returnclass = 'sf')%>%
  filter(name == "Victoria")

p = ggplot(d) +
  geom_sf(data = vic_map) +
  geom_point(aes(x = lon, y = lat), alpha = 0.2) + 
  transition_time(obsTime) +
  exit_fade() +
  enter_fade() +
  labs(title = 'Time: {frame_time}') +
  theme_bw()+
  theme(legend.position = 'none')
animate(p)
anim_save(filename = 'all.gif',path = "./www/")
```





```{r}
d <- read_csv("data/hotspot_2008_2009.csv")%>%
  as.data.frame()

result <- hotspot_cluster(d,
  lon = "lon",
  lat = "lat",
  obsTime = 'obsTime',
  activeTime = 24,
  adjDist = 3000,
  minPts = 4,
  minTime = 3,
  ignitionCenter = "mean",
  timeUnit = "h",
  timeStep = 1
)

result_data <- result$hotspots%>%
  mutate(membership = as.factor(membership))

result_data2 <- result_data%>%
  select(lon,lat,membership)

vic_map = ne_states(country = 'Australia', returnclass = 'sf')%>%
  filter(name == "Victoria")

p = ggplot(result_data) +
  geom_sf(data = vic_map, fill = "#2D2C2C",colour="white") +
  xlim(c(140, 150.5)) + ylim(c(-39.5, -33.5)) +
  ggtitle("Monthly Average Temperature") +
  theme_map() +
  exit_fade() +
  enter_fade() +
  #theme(panel.background = element_blank())+
  theme(legend.position="none")+
  geom_point(mapping = aes(x = lon, y = lat,color = membership)
             , alpha = 0.2)+
  transition_states(obsTime) +
  labs(title = 'Time: {closest_state}',size = 12)


animate(p,fps = 5)
anim_save(filename = '2008_2009.gif',path = "./www/")
```


```{r}
d <- read_csv("data/hotspot_2009_2010.csv")%>%
  as.data.frame()

result <- hotspot_cluster(d,
  lon = "lon",
  lat = "lat",
  obsTime = 'obsTime',
  activeTime = 24,
  adjDist = 3000,
  minPts = 4,
  minTime = 3,
  ignitionCenter = "mean",
  timeUnit = "h",
  timeStep = 1
)

result_data <- result$hotspots%>%
  mutate(membership = as.factor(membership))

result_data2 <- result_data%>%
  select(lon,lat,membership)

vic_map = ne_states(country = 'Australia', returnclass = 'sf')%>%
  filter(name == "Victoria")

p = ggplot(result_data) +
  geom_sf(data = vic_map, fill = "#2D2C2C",colour="white") +
  xlim(c(140, 150.5)) + ylim(c(-39.5, -33.5)) +
  ggtitle("Monthly Average Temperature") +
  theme_map() +
  exit_fade() +
  enter_fade() +
  #theme(panel.background = element_blank())+
  theme(legend.position="none")+
  geom_point(mapping = aes(x = lon, y = lat,color = membership)
             , alpha = 0.2)+
  transition_states(obsTime) +
  labs(title = 'Time: {closest_state}',size = 12)


animate(p,fps = 5)
anim_save(filename = '2009_2010.gif',path = "./www/")
``` 



```{r}
d <- read_csv("data/hotspot_2010_2011.csv")%>%
  as.data.frame()

result <- hotspot_cluster(d,
  lon = "lon",
  lat = "lat",
  obsTime = 'obsTime',
  activeTime = 24,
  adjDist = 3000,
  minPts = 4,
  minTime = 3,
  ignitionCenter = "mean",
  timeUnit = "h",
  timeStep = 1
)

result_data <- result$hotspots%>%
  mutate(membership = as.factor(membership))

result_data2 <- result_data%>%
  select(lon,lat,membership)

vic_map = ne_states(country = 'Australia', returnclass = 'sf')%>%
  filter(name == "Victoria")

p = ggplot(result_data) +
  geom_sf(data = vic_map, fill = "#2D2C2C",colour="white") +
  xlim(c(140, 150.5)) + ylim(c(-39.5, -33.5)) +
  ggtitle("Monthly Average Temperature") +
  theme_map() +
  exit_fade() +
  enter_fade() +
  #theme(panel.background = element_blank())+
  theme(legend.position="none")+
  geom_point(mapping = aes(x = lon, y = lat,color = membership)
             , alpha = 0.2)+
  transition_states(obsTime) +
  labs(title = 'Time: {closest_state}',size = 12)


animate(p,fps = 5)
anim_save(filename = '2010_2011.gif',path = "./www/")
```



```{r}
d <- read_csv("data/hotspot_2011_2012.csv")%>%
  as.data.frame()

result <- hotspot_cluster(d,
  lon = "lon",
  lat = "lat",
  obsTime = 'obsTime',
  activeTime = 24,
  adjDist = 3000,
  minPts = 4,
  minTime = 3,
  ignitionCenter = "mean",
  timeUnit = "h",
  timeStep = 1
)

result_data <- result$hotspots%>%
  mutate(membership = as.factor(membership))

result_data2 <- result_data%>%
  select(lon,lat,membership)

vic_map = ne_states(country = 'Australia', returnclass = 'sf')%>%
  filter(name == "Victoria")

p = ggplot(result_data) +
  geom_sf(data = vic_map, fill = "#2D2C2C",colour="white") +
  xlim(c(140, 150.5)) + ylim(c(-39.5, -33.5)) +
  ggtitle("Monthly Average Temperature") +
  theme_map() +
  exit_fade() +
  enter_fade() +
  #theme(panel.background = element_blank())+
  theme(legend.position="none")+
  geom_point(mapping = aes(x = lon, y = lat,color = membership)
             , alpha = 0.2)+
  transition_states(obsTime) +
  labs(title = 'Time: {closest_state}',size = 12)


animate(p,fps = 5)
anim_save(filename = '2011_2012.gif',path = "./www/")
```



```{r}
d <- read_csv("data/hotspot_2012_2013.csv")%>%
  as.data.frame()

result <- hotspot_cluster(d,
  lon = "lon",
  lat = "lat",
  obsTime = 'obsTime',
  activeTime = 24,
  adjDist = 3000,
  minPts = 4,
  minTime = 3,
  ignitionCenter = "mean",
  timeUnit = "h",
  timeStep = 1
)

result_data <- result$hotspots%>%
  mutate(membership = as.factor(membership))

result_data2 <- result_data%>%
  select(lon,lat,membership)

vic_map = ne_states(country = 'Australia', returnclass = 'sf')%>%
  filter(name == "Victoria")

p = ggplot(result_data) +
  geom_sf(data = vic_map, fill = "#2D2C2C",colour="white") +
  xlim(c(140, 150.5)) + ylim(c(-39.5, -33.5)) +
  ggtitle("Monthly Average Temperature") +
  theme_map() +
  exit_fade() +
  enter_fade() +
  #theme(panel.background = element_blank())+
  theme(legend.position="none")+
  geom_point(mapping = aes(x = lon, y = lat,color = membership)
             , alpha = 0.2)+
  transition_states(obsTime) +
  labs(title = 'Time: {closest_state}',size = 12)


animate(p,fps = 5)
anim_save(filename = '2012_2013.gif',path = "./www/")
```



```{r}
d <- read_csv("data/hotspot_2013_2014.csv")%>%
  as.data.frame()

result <- hotspot_cluster(d,
  lon = "lon",
  lat = "lat",
  obsTime = 'obsTime',
  activeTime = 24,
  adjDist = 3000,
  minPts = 4,
  minTime = 3,
  ignitionCenter = "mean",
  timeUnit = "h",
  timeStep = 1
)

result_data <- result$hotspots%>%
  mutate(membership = as.factor(membership))

result_data2 <- result_data%>%
  select(lon,lat,membership)

vic_map = ne_states(country = 'Australia', returnclass = 'sf')%>%
  filter(name == "Victoria")

p = ggplot(result_data) +
  geom_sf(data = vic_map, fill = "#2D2C2C",colour="white") +
  xlim(c(140, 150.5)) + ylim(c(-39.5, -33.5)) +
  ggtitle("Monthly Average Temperature") +
  theme_map() +
  exit_fade() +
  enter_fade() +
  #theme(panel.background = element_blank())+
  theme(legend.position="none")+
  geom_point(mapping = aes(x = lon, y = lat,color = membership)
             , alpha = 0.2)+
  transition_states(obsTime) +
  labs(title = 'Time: {closest_state}',size = 12)


animate(p,fps = 5)
anim_save(filename = '2013_2014.gif',path = "./www/")
```



```{r}
d <- read_csv("data/hotspot_2014_2015.csv")%>%
  as.data.frame()

result <- hotspot_cluster(d,
  lon = "lon",
  lat = "lat",
  obsTime = 'obsTime',
  activeTime = 24,
  adjDist = 3000,
  minPts = 4,
  minTime = 3,
  ignitionCenter = "mean",
  timeUnit = "h",
  timeStep = 1
)

result_data <- result$hotspots%>%
  mutate(membership = as.factor(membership))

result_data2 <- result_data%>%
  select(lon,lat,membership)

vic_map = ne_states(country = 'Australia', returnclass = 'sf')%>%
  filter(name == "Victoria")

p = ggplot(result_data) +
  geom_sf(data = vic_map, fill = "#2D2C2C",colour="white") +
  xlim(c(140, 150.5)) + ylim(c(-39.5, -33.5)) +
  ggtitle("Monthly Average Temperature") +
  theme_map() +
  exit_fade() +
  enter_fade() +
  #theme(panel.background = element_blank())+
  theme(legend.position="none")+
  geom_point(mapping = aes(x = lon, y = lat,color = membership)
             , alpha = 0.2)+
  transition_states(obsTime) +
  labs(title = 'Time: {closest_state}',size = 12)


animate(p,fps = 5)
anim_save(filename = '2014_2015.gif',path = "./www/")
```


```{r}
d <- read_csv("data/hotspot_2015_2016.csv")%>%
  as.data.frame()

result <- hotspot_cluster(d,
  lon = "lon",
  lat = "lat",
  obsTime = 'obsTime',
  activeTime = 24,
  adjDist = 3000,
  minPts = 4,
  minTime = 3,
  ignitionCenter = "mean",
  timeUnit = "h",
  timeStep = 1
)

result_data <- result$hotspots%>%
  mutate(membership = as.factor(membership))

result_data2 <- result_data%>%
  select(lon,lat,membership)

vic_map = ne_states(country = 'Australia', returnclass = 'sf')%>%
  filter(name == "Victoria")

p = ggplot(result_data) +
  geom_sf(data = vic_map, fill = "#2D2C2C",colour="white") +
  xlim(c(140, 150.5)) + ylim(c(-39.5, -33.5)) +
  ggtitle("Monthly Average Temperature") +
  theme_map() +
  exit_fade() +
  enter_fade() +
  #theme(panel.background = element_blank())+
  theme(legend.position="none")+
  geom_point(mapping = aes(x = lon, y = lat,color = membership)
             , alpha = 0.2)+
  transition_states(obsTime) +
  labs(title = 'Time: {closest_state}',size = 12)


animate(p,fps = 5)
anim_save(filename = '2015_2016.gif',path = "./www/")
```


```{r}
d <- read_csv("data/hotspot_2016_2017.csv")%>%
  as.data.frame()

result <- hotspot_cluster(d,
  lon = "lon",
  lat = "lat",
  obsTime = 'obsTime',
  activeTime = 24,
  adjDist = 3000,
  minPts = 4,
  minTime = 3,
  ignitionCenter = "mean",
  timeUnit = "h",
  timeStep = 1
)

result_data <- result$hotspots%>%
  mutate(membership = as.factor(membership))

result_data2 <- result_data%>%
  select(lon,lat,membership)

vic_map = ne_states(country = 'Australia', returnclass = 'sf')%>%
  filter(name == "Victoria")

p = ggplot(result_data) +
  geom_sf(data = vic_map, fill = "#2D2C2C",colour="white") +
  xlim(c(140, 150.5)) + ylim(c(-39.5, -33.5)) +
  ggtitle("Monthly Average Temperature") +
  theme_map() +
  exit_fade() +
  enter_fade() +
  #theme(panel.background = element_blank())+
  theme(legend.position="none")+
  geom_point(mapping = aes(x = lon, y = lat,color = membership)
             , alpha = 0.2)+
  transition_states(obsTime) +
  labs(title = 'Time: {closest_state}',size = 12)


animate(p,fps = 5)
anim_save(filename = '2016_2017.gif',path = "./www/")
```


```{r}
d <- read_csv("data/hotspot_2017_2018.csv")%>%
  as.data.frame()

result <- hotspot_cluster(d,
  lon = "lon",
  lat = "lat",
  obsTime = 'obsTime',
  activeTime = 24,
  adjDist = 3000,
  minPts = 4,
  minTime = 3,
  ignitionCenter = "mean",
  timeUnit = "h",
  timeStep = 1
)

result_data <- result$hotspots%>%
  mutate(membership = as.factor(membership))

result_data2 <- result_data%>%
  select(lon,lat,membership)

vic_map = ne_states(country = 'Australia', returnclass = 'sf')%>%
  filter(name == "Victoria")

p = ggplot(result_data) +
  geom_sf(data = vic_map, fill = "#2D2C2C",colour="white") +
  xlim(c(140, 150.5)) + ylim(c(-39.5, -33.5)) +
  ggtitle("Monthly Average Temperature") +
  theme_map() +
  exit_fade() +
  enter_fade() +
  #theme(panel.background = element_blank())+
  theme(legend.position="none")+
  geom_point(mapping = aes(x = lon, y = lat,color = membership)
             , alpha = 0.2)+
  transition_states(obsTime) +
  labs(title = 'Time: {closest_state}',size = 12)


animate(p,fps = 5)
anim_save(filename = '2017_2018.gif',path = "./www/")
```

```{r}
d <- read_csv("data/hotspot_2018_2019.csv")%>%
  as.data.frame()

result <- hotspot_cluster(d,
  lon = "lon",
  lat = "lat",
  obsTime = 'obsTime',
  activeTime = 24,
  adjDist = 3000,
  minPts = 4,
  minTime = 3,
  ignitionCenter = "mean",
  timeUnit = "h",
  timeStep = 1
)

result_data <- result$hotspots%>%
  mutate(membership = as.factor(membership))

result_data2 <- result_data%>%
  select(lon,lat,membership)

vic_map = ne_states(country = 'Australia', returnclass = 'sf')%>%
  filter(name == "Victoria")

p = ggplot(result_data) +
  geom_sf(data = vic_map, fill = "#2D2C2C",colour="white") +
  xlim(c(140, 150.5)) + ylim(c(-39.5, -33.5)) +
  ggtitle("Monthly Average Temperature") +
  theme_map() +
  exit_fade() +
  enter_fade() +
  #theme(panel.background = element_blank())+
  theme(legend.position="none")+
  geom_point(mapping = aes(x = lon, y = lat,color = membership)
             , alpha = 0.2)+
  transition_states(obsTime) +
  labs(title = 'Time: {closest_state}',size = 12)


animate(p,fps = 5)
anim_save(filename = '2018_2019.gif',path = "./www/")
```


```{r}
d <- read_csv("data/hotspot_2020_2021.csv")%>%
  as.data.frame()

result <- hotspot_cluster(d,
  lon = "lon",
  lat = "lat",
  obsTime = 'obsTime',
  activeTime = 24,
  adjDist = 3000,
  minPts = 4,
  minTime = 3,
  ignitionCenter = "mean",
  timeUnit = "h",
  timeStep = 1
)

result_data <- result$hotspots%>%
  mutate(membership = as.factor(membership))

result_data2 <- result_data%>%
  select(lon,lat,membership)

vic_map = ne_states(country = 'Australia', returnclass = 'sf')%>%
  filter(name == "Victoria")

p = ggplot(result_data) +
  geom_sf(data = vic_map, fill = "#2D2C2C",colour="white") +
  xlim(c(140, 150.5)) + ylim(c(-39.5, -33.5)) +
  ggtitle("Monthly Average Temperature") +
  theme_map() +
  exit_fade() +
  enter_fade() +
  #theme(panel.background = element_blank())+
  theme(legend.position="none")+
  geom_point(mapping = aes(x = lon, y = lat,color = membership)
             , alpha = 0.2)+
  transition_states(obsTime) +
  labs(title = 'Time: {closest_state}',size = 12)


animate(p,fps = 5)
anim_save(filename = '2020_2021.gif',path = "./www/")
```

```{r}
d <- read_csv("data/hotspot_2021_2022.csv")%>%
  as.data.frame()

result <- hotspot_cluster(d,
  lon = "lon",
  lat = "lat",
  obsTime = 'obsTime',
  activeTime = 24,
  adjDist = 3000,
  minPts = 4,
  minTime = 3,
  ignitionCenter = "mean",
  timeUnit = "h",
  timeStep = 1
)

result_data <- result$hotspots%>%
  mutate(membership = as.factor(membership))

result_data2 <- result_data%>%
  select(lon,lat,membership)

vic_map = ne_states(country = 'Australia', returnclass = 'sf')%>%
  filter(name == "Victoria")

p = ggplot(result_data) +
  geom_sf(data = vic_map, fill = "#2D2C2C",colour="white") +
  xlim(c(140, 150.5)) + ylim(c(-39.5, -33.5)) +
  ggtitle("Monthly Average Temperature") +
  theme_map() +
  exit_fade() +
  enter_fade() +
  #theme(panel.background = element_blank())+
  theme(legend.position="none")+
  geom_point(mapping = aes(x = lon, y = lat,color = membership)
             , alpha = 0.2)+
  transition_states(obsTime) +
  labs(title = 'Time: {closest_state}',size = 12)


animate(p,fps = 5)
anim_save(filename = '2021_2022.gif',path = "./www/")
```


