---
title: "cluster"
author: "yiru wang"
date: '2022-10-12'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(sf)
library(DT)
library(furrr)
library(lubridate)
library(rnaturalearth)
library(dplyr)
library(geojsonsf)
library(shinydashboard)
library(gganimate)
library(dashboardthemes)
library(shiny)
library(shinycustomloader)

# Define UI for application that draws a histogram
library(leaflet)
library(formattable)
library(cranlogs)
```


```{r}
recent_hotspot_data <- geojsonsf::geojson_sf("https://hotspots.dea.ga.gov.au/data/recent-hotspots.json")
```


```{r}
data <- recent_hotspot_data %>%
 select(latitude,temp_kelvin,datetime,longitude,
        satellite,confidence,australian_state,geometry)
  
```


```{r}

    data$datetime <- str_replace(data$datetime,"T"," ")
    data$datetime <- str_replace(data$datetime,"Z"," ")
    data$datetime <- as_datetime(data$datetime) + dhours(10)
    data
```

```{r}
cluster <- data %>%
  select(latitude,datetime,longitude)
cluster_scale <- scale(cluster)
cluster <- dist(cluster_scale)
```

```{r}
data_new <- data %>%
 mutate(time = as.numeric(Sys.time() - datetime,units = "mins"))%>%
  filter(time <= 20)
```


```{r}
head(data_new)
```

```{r}
all_data <- read_csv("./hotspot_historic.csv")
```

```{r}
smaller_data = all_data %>%
  filter(between(longitude, 112, 155)) %>% 
  filter(between(latitude, -44, -10))

```

```{r}
write.csv(smaller_data, "./smaller_data.csv")
```

```{r}
smaller_data%>%
  count(australian_state)
```

```{r}
smaller_data = st_as_sf(x = smaller_data, coords = c('longitude','latitude'))
st_crs(smaller_data) = 4326
```


```{r}
au_map <-ne_states(country = c("australia"), returnclass ="sf")%>%
  select(state = name, geometry)
vic_map <- au_map%>%
  filter(state == "Victoria")
vic_hist_hotspot = st_intersects(vic_map$geometry, smaller_data$geometry)
vic_hist_hotspot = smaller_data[vic_hist_hotspot[[1]],]
```

```{r}
write.csv(vic_hist_hotspot, "./vic_hist_hotspot.csv")
```

```{r}
head(all_data,5)
```

```{r}
all_data%>%
  count(australian_state)

```


```{r}
spot_spot <- read_csv("./2020-2021hotpots.csv")
```

```{r}
vic_data <- read_csv("./vic_hist_hotspot.csv")
```

```{r}
vic_data <- vic_data%>%
  mutate(datetime = as.Date(datetime))
```

```{r}
head(vic_data,5)
```



```{r}
hotspot_2019_2020<- vic_data%>%
  mutate(date = as.Date(datetime))%>%
  mutate(obsTime = as_datetime(datetime))%>%
  mutate(obsTime = as.POSIXct(obsTime))%>%
  extract(geometry, c('lat', 'lon'), '\\((.*), (.*)\\)', convert = TRUE) %>%
  mutate(year = "2019-2020")%>%
  filter(date <="2020-2-28")%>%
  filter("2019-10-01"<= date)
```

```{r}
hotspot_2020_2021<- vic_data%>%
  mutate(date = as.Date(datetime))%>%
  mutate(obsTime = as_datetime(datetime))%>%
  mutate(obsTime = as.POSIXct(obsTime))%>%
  extract(geometry, c('lat', 'lon'), '\\((.*), (.*)\\)', convert = TRUE) %>%
  mutate(year = "2020-2021")%>%
  filter(date <="2021-2-28")%>%
  filter("2020-10-01"<= date)
```

```{r}
hotspot_2018_2019<- vic_data%>%
  mutate(date = as.Date(datetime))%>%
  mutate(obsTime = as_datetime(datetime))%>%
  mutate(obsTime = as.POSIXct(obsTime))%>%
  extract(geometry, c('lat', 'lon'), '\\((.*), (.*)\\)', convert = TRUE) %>%
  mutate(year = "2018-2019")%>%
  filter(date <="2019-2-28")%>%
  filter("2018-10-01"<= date)
```

```{r}
hotspot_2017_2018<- vic_data%>%
  mutate(date = as.Date(datetime))%>%
  mutate(obsTime = as_datetime(datetime))%>%
  mutate(obsTime = as.POSIXct(obsTime))%>%
  extract(geometry, c('lat', 'lon'), '\\((.*), (.*)\\)', convert = TRUE) %>%
  mutate(year = "2017-2018")%>%
  filter(date <="2018-2-28")%>%
  filter("2017-10-01"<= date)
```

```{r}
hotspot_2016_2017<- vic_data%>%
  mutate(date = as.Date(datetime))%>%
  mutate(obsTime = as_datetime(datetime))%>%
  mutate(obsTime = as.POSIXct(obsTime))%>%
  extract(geometry, c('lat', 'lon'), '\\((.*), (.*)\\)', convert = TRUE) %>%
  mutate(year = "2016-2017")%>%
  filter(date <="2017-2-28")%>%
  filter("2016-10-01"<= date)
```

```{r}
hotspot_2015_2016<- vic_data%>%
  mutate(date = as.Date(datetime))%>%
  mutate(obsTime = as_datetime(datetime))%>%
  mutate(obsTime = as.POSIXct(obsTime))%>%
  extract(geometry, c('lat', 'lon'), '\\((.*), (.*)\\)', convert = TRUE) %>%
  mutate(year = "2015-2016")%>%
  filter(date <="2016-2-28")%>%
  filter("2015-10-01"<= date)
```

```{r}
hotspot_2014_2015<- vic_data%>%
  mutate(date = as.Date(datetime))%>%
  mutate(obsTime = as_datetime(datetime))%>%
  mutate(obsTime = as.POSIXct(obsTime))%>%
  extract(geometry, c('lat', 'lon'), '\\((.*), (.*)\\)', convert = TRUE) %>%
  mutate(year = "2014-2015")%>%
  filter(date <="2015-2-28")%>%
  filter("2014-10-01"<= date)
```

```{r}
hotspot_2013_2014<- vic_data%>%
  mutate(date = as.Date(datetime))%>%
  mutate(obsTime = as_datetime(datetime))%>%
  mutate(obsTime = as.POSIXct(obsTime))%>%
  extract(geometry, c('lat', 'lon'), '\\((.*), (.*)\\)', convert = TRUE) %>%
  mutate(year = "2013-2014")%>%
  filter(date <="2014-2-28")%>%
  filter("2013-10-01"<= date)
```

```{r}
hotspot_2012_2013<- vic_data%>%
  mutate(date = as.Date(datetime))%>%
  mutate(obsTime = as_datetime(datetime))%>%
  mutate(obsTime = as.POSIXct(obsTime))%>%
  extract(geometry, c('lat', 'lon'), '\\((.*), (.*)\\)', convert = TRUE) %>%
  mutate(year = "2012-2013")%>%
  filter(date <="2013-2-28")%>%
  filter("2012-10-01"<= date)
```

```{r}
hotspot_2011_2012<- vic_data%>%
  mutate(date = as.Date(datetime))%>%
  mutate(obsTime = as_datetime(datetime))%>%
  mutate(obsTime = as.POSIXct(obsTime))%>%
  extract(geometry, c('lat', 'lon'), '\\((.*), (.*)\\)', convert = TRUE) %>%
  mutate(year = "2011-2012")%>%
  filter(date <="2012-2-28")%>%
  filter("2011-10-01"<= date)
```

```{r}
hotspot_2010_2011<- vic_data%>%
  mutate(date = as.Date(datetime))%>%
  mutate(obsTime = as_datetime(datetime))%>%
  mutate(obsTime = as.POSIXct(obsTime))%>%
  extract(geometry, c('lat', 'lon'), '\\((.*), (.*)\\)', convert = TRUE) %>%
  mutate(year = "2010-2011")%>%
  filter(date <="2011-2-28")%>%
  filter("2010-10-01"<= date)
```

```{r}
hotspot_2021_2022<- vic_data%>%
  mutate(date = as.Date(datetime))%>%
  mutate(obsTime = as_datetime(datetime))%>%
  mutate(obsTime = as.POSIXct(obsTime))%>%
  extract(geometry, c('lat', 'lon'), '\\((.*), (.*)\\)', convert = TRUE) %>%
  mutate(year = "2021-2022")%>%
  filter(date <="2022-2-28")%>%
  filter("2021-10-01"<= date)
```

```{r}
write.csv(hotspot_2011_2012, "./hotspot_2011_2012.csv")
write.csv(hotspot_2012_2013, "./hotspot_2012_2013.csv")
write.csv(hotspot_2013_2014, "./hotspot_2013_2014.csv")
write.csv(hotspot_2014_2015, "./hotspot_2014_2015.csv")
write.csv(hotspot_2015_2016, "./hotspot_2015_2016.csv")
write.csv(hotspot_2016_2017, "./hotspot_2016_2017.csv")
write.csv(hotspot_2017_2018, "./hotspot_2017_2018.csv")
write.csv(hotspot_2018_2019, "./hotspot_2018_2019.csv")
write.csv(hotspot_2019_2020, "./hotspot_2019_2020.csv")
write.csv(hotspot_2020_2021, "./hotspot_2020_2021.csv")
write.csv(hotspot_2021_2022, "./hotspot_2021_2022.csv")
```


```{r}
min(vic_data$datetime)
```

```{r}
hotspot_2002_2003<- vic_data%>%
  mutate(date = as.Date(datetime))%>%
  mutate(obsTime = as_datetime(datetime))%>%
  mutate(obsTime = as.POSIXct(obsTime))%>%
  extract(geometry, c('lat', 'lon'), '\\((.*), (.*)\\)', convert = TRUE) %>%
  mutate(year = "2002-2003")%>%
  filter(date <="2003-2-28")%>%
  filter("2002-10-01"<= date)
```

```{r}
hotspot_2003_2004<- vic_data%>%
  mutate(date = as.Date(datetime))%>%
  mutate(obsTime = as_datetime(datetime))%>%
  mutate(obsTime = as.POSIXct(obsTime))%>%
  extract(geometry, c('lat', 'lon'), '\\((.*), (.*)\\)', convert = TRUE) %>%
  mutate(year = "2019-2020")%>%
  filter(date <="2004-2-28")%>%
  filter("2003-10-01"<= date)
```

```{r}
hotspot_2004_2005<- vic_data%>%
  mutate(date = as.Date(datetime))%>%
  filter(date <="2005-2-28")%>%
  filter("2004-10-01"<= date)
```

```{r}
hotspot_2005_2006<- vic_data%>%
  mutate(date = as.Date(datetime))%>%
  filter(date <="2006-2-28")%>%
  filter("2005-10-01"<= date)
```

```{r}
hotspot_2006_2007<- vic_data%>%
  mutate(date = as.Date(datetime))%>%
  filter(date <="2007-2-28")%>%
  filter("2006-10-01"<= date)
```

```{r}
hotspot_2007_2008<- vic_data%>%
  mutate(date = as.Date(datetime))%>%
  filter(date <="2008-2-28")%>%
  filter("2007-10-01"<= date)
```


```{r}
hotspot_2008_2009<- vic_data%>%
  mutate(date = as.Date(datetime))%>%
  filter(date <="2009-2-28")%>%
  filter("2008-10-01"<= date)
```

```{r}
hotspot_2009_2010<- vic_data%>%
  mutate(date = as.Date(datetime))%>%
  filter(date <="2010-2-28")%>%
  filter("2009-10-01"<= date)
```

```{r}
hotspot_2010_2011<- vic_data%>%
  mutate(date = as.Date(datetime))%>%
  filter(date <="2011-2-28")%>%
  filter("2010-10-01"<= date)
```


```{r}
write.csv(hotspot_2010_2011, "./hotspot_2010_2011.csv")
write.csv(hotspot_2009_2010, "./hotspot_2009_2010.csv")
write.csv(hotspot_2008_2009, "./hotspot_2008_2009.csv")
write.csv(hotspot_2007_2008, "./hotspot_2007_2008.csv")
write.csv(hotspot_2006_2007, "./hotspot_2006_2007.csv")
write.csv(hotspot_2005_2006, "./hotspot_2005_2006.csv")
write.csv(hotspot_2004_2005, "./hotspot_2004_2005.csv")
write.csv(hotspot_2003_2004, "./hotspot_2003_2004.csv")
write.csv(hotspot_2002_2003, "./hotspot_2002_2003.csv")
```


```{r}
library(spotoroo)
library(tidyverse)
library(sf)
```

```{r}
recent_hotspot_data <- geojsonsf::geojson_sf("https://hotspots.dea.ga.gov.au/data/recent-hotspots.json")
```


```{r}
qld <- recent_hotspot_data %>%
  st_transform( sf::st_crs("+proj=longlat +datum=WGS84")) %>% geometry_to_lonlat
```
```{r}
library(tidyverse)
library(sf)
library(DT)
library(furrr)
library(lubridate)
library(rnaturalearth)
library(dplyr)
library(geojsonsf)
library(shinydashboard)
library(gganimate)
library(dashboardthemes)
library(shiny)
library(shinycustomloader)
library(shinyjs)
library(shinyBS)
library(rintrojs)
# Define UI for application that draws a histogram
library(leaflet)
library(formattable)
library(cranlogs)
```

```{r}
au_map <-ne_states(country = c("australia"), returnclass ="sf")%>%
    select(state = name, geometry)
  vic_map <- au_map%>%
    filter(state == "Victoria")
```

```{r}
test <- read.csv("./hotspot_2002_2003.csv")%>%
  mutate(date = as.Date(date))
```

```{r}
ggplot()+
    geom_sf(data = vic_map)+
    geom_point(data = test, aes(longitude, latitude),color = "red")+
    theme_bw() +
    transition_states(date)+
    enter_recolor(fill = "#f0f5f9") +
    labs(subtitle = "Date:{previous_state}")
```

```{r}
 hotspot_2002_2003<- read.csv("./all_data/hotspot_2002_2003.csv")%>%
  mutate(date = as.Date(date))%>%
  mutate(year ="2002-2003")
hotspot_2003_2004<- read.csv("./all_data/hotspot_2003_2004.csv")%>%
  mutate(date = as.Date(date))%>%
  mutate(year ="2003-2004")
hotspot_2004_2005<- read.csv("./all_data/hotspot_2004_2005.csv")%>%
  mutate(date = as.Date(date))%>%
  mutate(year ="2004-2005")
hotspot_2005_2006<- read.csv("./all_data/hotspot_2005_2006.csv")%>%
  mutate(date = as.Date(date))%>%
  mutate(year ="2005-2006")
hotspot_2006_2007<- read.csv("./all_data/hotspot_2006_2007.csv")%>%
  mutate(date = as.Date(date))%>%
  mutate(year ="2006-2007")
hotspot_2007_2008<- read.csv("./all_data/hotspot_2007_2008.csv")%>%
  mutate(date = as.Date(date))%>%
  mutate(year ="2007-2008")
hotspot_2008_2009<- read.csv("./all_data/hotspot_2008_2009.csv")%>%
  mutate(date = as.Date(date))%>%
  mutate(year ="2008-2009")
hotspot_2009_2010<- read.csv("./all_data/hotspot_2009_2010.csv")%>%
  mutate(date = as.Date(date))%>%
  mutate(year ="2009-2010")
hotspot_2010_2011<- read.csv("./all_data/hotspot_2010_2011.csv")%>%
  mutate(date = as.Date(date))%>%
  mutate(year ="2010-2011")
hotspot_2011_2012<- read.csv("./all_data/hotspot_2011_2012.csv")%>%
  mutate(date = as.Date(date))%>%
  mutate(year ="2011-2012")
hotspot_2012_2013<- read.csv("./all_data/hotspot_2012_2013.csv")%>%
  mutate(date = as.Date(date))%>%
  mutate(year ="2012-2013")
hotspot_2013_2014<- read.csv("./all_data/hotspot_2013_2014.csv")%>%
  mutate(date = as.Date(date))%>%
  mutate(year ="2013-2014")
hotspot_2014_2015<- read.csv("./all_data/hotspot_2014_2015.csv")%>%
  mutate(date = as.Date(date))%>%
  mutate(year ="2014-2015")
hotspot_2015_2016<- read.csv("./all_data/hotspot_2015_2016.csv")%>%
  mutate(date = as.Date(date))%>%
  mutate(year ="2015-2016")
hotspot_2016_2017<- read.csv("./all_data/hotspot_2016_2017.csv")%>%
  mutate(date = as.Date(date))%>%
  mutate(year ="2016-2017")
hotspot_2017_2018<- read.csv("./all_data/hotspot_2017_2018.csv")%>%
  mutate(date = as.Date(date))%>%
  mutate(year ="2017-2018")
hotspot_2018_2019<- read.csv("./all_data/hotspot_2018_2019.csv")%>%
  mutate(date = as.Date(date))%>%
  mutate(year ="2018-2019")
hotspot_2019_2020<- read.csv("./all_data/hotspot_2019_2020.csv")%>%
  mutate(date = as.Date(date))%>%
  mutate(year ="2019-2020")
hotspot_2020_2021<- read.csv("./all_data/hotspot_2020_2021.csv")%>%
  mutate(date = as.Date(date))%>%
  mutate(year ="2020-2021")
hotspot_2021_2022<- read.csv("./all_data/hotspot_2021_2022.csv")%>%
  mutate(date = as.Date(date))%>%
  mutate(year ="2021-2022")
a<- merge(hotspot_2002_2003,hotspot_2003_2004,all = TRUE)
b<- merge(hotspot_2004_2005,hotspot_2005_2006,all = TRUE)
c<- merge(hotspot_2006_2007,hotspot_2007_2008,all = TRUE)
d<- merge(hotspot_2008_2009,hotspot_2009_2010,all = TRUE)
e<- merge(hotspot_2010_2011,hotspot_2011_2012,all = TRUE)
f<- merge(hotspot_2012_2013,hotspot_2013_2014,all = TRUE)
g<- merge(hotspot_2014_2015,hotspot_2015_2016,all = TRUE)
h<- merge(hotspot_2016_2017,hotspot_2017_2018,all = TRUE)
i<- merge(hotspot_2018_2019,hotspot_2019_2020,all = TRUE)
ab <- merge(a,b,all = TRUE)
cd <-merge(c,d,all = TRUE)
ef<- merge(e,f,all = TRUE)
gh <- merge(g,h,all=TRUE)
ii <- merge(i,hotspot_2020_2021,all=TRUE)
abcd <- merge(ab,cd,all = TRUE)
efgh <- merge(ef,gh,all = TRUE)
ah <-merge(abcd,efgh,all = TRUE)
hist_data <- merge(ah,ii,all = TRUE)
hist_data2 <- merge(hist_data,hotspot_2021_2022,all = TRUE)
```

```{r}
write.csv(hist_data2, "./hist_data.csv")
```


```{r}
vic_data <- read.csv("./vic_data.csv")%>%
  mutate(date = as.Date(datetime))%>%
  filter(date <="2017-2-28")%>%
  filter("2015-10-01"<= date)
```

```{r}
test <- read_csv("data/hotspot_2008_2009.csv")
```

```{r}
test2 <- test%>%
  mutate(start_time = as_datetime("2008-10-01 00:00:00"))%>%
  mutate(since_start_time = as.numeric(obsTime - start_time,units = "hours",digits = 0))
```

```{r}
test2$since_start_time<-round(test2$since_start_time,0)
```

```{r}
bkgd_map <- ggplot() + 
      geom_density_2d_filled(data=test2, aes(x=lon, y=lat)) +
      geom_sf(data = vic_map, colour="white", fill=NA) +
      xlim(c(140, 150.5)) + ylim(c(-39.5, -33.5)) +
      scale_fill_grey() +
      theme_map() +
      theme(legend.position="none")
    # save(bkgd_map, file="bkgd_map.rda")  
    # 
    # load("bkgd_map.rda")
    
    plot<- bkgd_map +
      geom_point(test2 %>% dplyr::filter(since_start_time ==2893), 
                 mapping=aes(x=lon, y=lat), 
                 colour="orange") 
    plot
```

```{r}
map2_data <- read_csv("data/hotspot_2008_2009.csv")%>%
        mutate(start_time = as_datetime("2008-10-01 00:00:00"))%>%
        mutate(since_start_time = as.numeric(obsTime - start_time,units = "hours"))
map2_data$since_start_time<-round(map2_data$since_start_time,0)
```

```{r}
plot <- ggplot() + 
      geom_density_2d_filled(data=map2_data, aes(x=lon, y=lat)) +
      geom_sf(data = vic_map, colour="white", fill=NA) +
      xlim(c(140, 150.5)) + ylim(c(-39.5, -33.5)) +
      scale_fill_grey() +
      theme_map() +
      theme(legend.position="none")+
      geom_point(map2_data %>% dplyr::filter(since_start_time == 701), 
                 mapping=aes(x=lon, y=lat), 
                 colour="orange") 
    
    plot
```

```{r}
au_map <-ne_states(country = c("australia"), returnclass ="sf")%>%
    select(state = name, geometry)
  vic_map <- au_map%>%
    filter(state == "Victoria")
vic_hotspot1 <- recent_hotspot_data %>%
      st_set_crs("WGS 84")
    vic_map <- vic_map %>%st_set_crs("WGS 84")
    recent_hotspot_data <- recent_hotspot_data %>%st_set_crs("WGS 84")
    vic_hotspot2 = st_intersects(vic_map$geometry, recent_hotspot_data$geometry)
    vic_hotspot2 = vic_hotspot1[vic_hotspot2[[1]],]

warning_data <- vic_hotspot2%>%
       select(latitude,temp_kelvin,datetime,longitude,
              satellite,confidence,australian_state,geometry)
     warning_data$datetime <- str_replace(warning_data$datetime,"T"," ")
     warning_data$datetime <- str_replace(warning_data$datetime,"Z"," ")
     warning_data$datetime <- as_datetime(warning_data$datetime)
     warning_data2 <- warning_data %>%
       mutate(time = as.numeric(Sys.time() - datetime,units = "mins"))%>%
       filter(time <= 20)
     
```


```{r}
result <- hotspot_cluster(warning_data,
                               lon = "longitude",
                               lat = "latitude",
                               obsTime = 'datetime',
                               activeTime = 24,
                               adjDist = 3000,
                               minPts = 4,
                               minTime = 3,
                               ignitionCenter = "mean",
                               timeUnit = "h",
                               timeStep = 1
     )
result_numbership <- max(result$ignition$membership)
```

```{r}
result_numbership
```






